[package]
name = "siminv"
version = "0.1.0-rc.1"
edition = "2024"

[dependencies]
bevy = "0.17.2"
serde = "1.0.228"

[dev-dependencies]
bevy_asset_loader = { version = "0.24.0-rc.1", features = ["2d"] }
bevy_pkv = "0.14"

[[example]]
name = "fantasy"

